// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrZoneAggreeHandlerFunc turns a function with the right signature into a zone aggree handler
type NrZoneAggreeHandlerFunc func(NrZoneAggreeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrZoneAggreeHandlerFunc) Handle(params NrZoneAggreeParams) middleware.Responder {
	return fn(params)
}

// NrZoneAggreeHandler interface for that can handle valid zone aggree params
type NrZoneAggreeHandler interface {
	Handle(NrZoneAggreeParams) middleware.Responder
}

// NewNrZoneAggree creates a new http.Handler for the zone aggree operation
func NewNrZoneAggree(ctx *middleware.Context, handler NrZoneAggreeHandler) *NrZoneAggree {
	return &NrZoneAggree{Context: ctx, Handler: handler}
}

/*NrZoneAggree swagger:route POST /zone/aggree Zone zoneAggree

同意加入圈子

同意加入圈子操作(圈主或管理员)

*/
type NrZoneAggree struct {
	Context *middleware.Context
	Handler NrZoneAggreeHandler
}

func (o *NrZoneAggree) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrZoneAggreeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
