// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrZoneQuiteHandlerFunc turns a function with the right signature into a zone quite handler
type NrZoneQuiteHandlerFunc func(NrZoneQuiteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrZoneQuiteHandlerFunc) Handle(params NrZoneQuiteParams) middleware.Responder {
	return fn(params)
}

// NrZoneQuiteHandler interface for that can handle valid zone quite params
type NrZoneQuiteHandler interface {
	Handle(NrZoneQuiteParams) middleware.Responder
}

// NewNrZoneQuite creates a new http.Handler for the zone quite operation
func NewNrZoneQuite(ctx *middleware.Context, handler NrZoneQuiteHandler) *NrZoneQuite {
	return &NrZoneQuite{Context: ctx, Handler: handler}
}

/*NrZoneQuite swagger:route POST /zone/quite Zone zoneQuite

退出圈子

退出圈子(圈子成员或管理员、圈主不可退出)

*/
type NrZoneQuite struct {
	Context *middleware.Context
	Handler NrZoneQuiteHandler
}

func (o *NrZoneQuite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrZoneQuiteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
