// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrZoneDropHandlerFunc turns a function with the right signature into a zone drop handler
type NrZoneDropHandlerFunc func(NrZoneDropParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrZoneDropHandlerFunc) Handle(params NrZoneDropParams) middleware.Responder {
	return fn(params)
}

// NrZoneDropHandler interface for that can handle valid zone drop params
type NrZoneDropHandler interface {
	Handle(NrZoneDropParams) middleware.Responder
}

// NewNrZoneDrop creates a new http.Handler for the zone drop operation
func NewNrZoneDrop(ctx *middleware.Context, handler NrZoneDropHandler) *NrZoneDrop {
	return &NrZoneDrop{Context: ctx, Handler: handler}
}

/*NrZoneDrop swagger:route POST /zone/drop Zone zoneDrop

解散圈子

解散圈子(圈主)

*/
type NrZoneDrop struct {
	Context *middleware.Context
	Handler NrZoneDropHandler
}

func (o *NrZoneDrop) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrZoneDropParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
