// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "injbackendapi/models"
)

// NewNrZoneAggreeParams creates a new NrZoneAggreeParams object
// with the default values initialized.
func NewNrZoneAggreeParams() NrZoneAggreeParams {
	var ()
	return NrZoneAggreeParams{}
}

// NrZoneAggreeParams contains all the bound params for the zone aggree operation
// typically these are obtained from a http.Request
//
// swagger:parameters /zone/aggree
type NrZoneAggreeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*以JSON的方式提交数据
	  In: body
	*/
	Body *models.Body5
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *NrZoneAggreeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Body5
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
