// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// ZoneReportOKCode is the HTTP code returned for type ZoneReportOK
const ZoneReportOKCode int = 200

/*ZoneReportOK 成功，返回成功信息

swagger:response zoneReportOK
*/
type ZoneReportOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewZoneReportOK creates ZoneReportOK with default headers values
func NewZoneReportOK() *ZoneReportOK {
	return &ZoneReportOK{}
}

// WithPayload adds the payload to the zone report o k response
func (o *ZoneReportOK) WithPayload(payload *models.InlineResponse2004) *ZoneReportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone report o k response
func (o *ZoneReportOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZoneReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrZoneReportDefault 返回错误

swagger:response zoneReportDefault
*/
type NrZoneReportDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrZoneReportDefault creates NrZoneReportDefault with default headers values
func NewNrZoneReportDefault(code int) *NrZoneReportDefault {
	if code <= 0 {
		code = 500
	}

	return &NrZoneReportDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the zone report default response
func (o *NrZoneReportDefault) WithStatusCode(code int) *NrZoneReportDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the zone report default response
func (o *NrZoneReportDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the zone report default response
func (o *NrZoneReportDefault) WithPayload(payload *models.Error) *NrZoneReportDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone report default response
func (o *NrZoneReportDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrZoneReportDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
