// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// ZoneShowOKCode is the HTTP code returned for type ZoneShowOK
const ZoneShowOKCode int = 200

/*ZoneShowOK 成功，返回成功信息

swagger:response zoneShowOK
*/
type ZoneShowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2001 `json:"body,omitempty"`
}

// NewZoneShowOK creates ZoneShowOK with default headers values
func NewZoneShowOK() *ZoneShowOK {
	return &ZoneShowOK{}
}

// WithPayload adds the payload to the zone show o k response
func (o *ZoneShowOK) WithPayload(payload *models.InlineResponse2001) *ZoneShowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone show o k response
func (o *ZoneShowOK) SetPayload(payload *models.InlineResponse2001) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZoneShowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrZoneShowDefault 返回错误

swagger:response zoneShowDefault
*/
type NrZoneShowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrZoneShowDefault creates NrZoneShowDefault with default headers values
func NewNrZoneShowDefault(code int) *NrZoneShowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrZoneShowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the zone show default response
func (o *NrZoneShowDefault) WithStatusCode(code int) *NrZoneShowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the zone show default response
func (o *NrZoneShowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the zone show default response
func (o *NrZoneShowDefault) WithPayload(payload *models.Error) *NrZoneShowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone show default response
func (o *NrZoneShowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrZoneShowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
