// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// ZoneMembersOKCode is the HTTP code returned for type ZoneMembersOK
const ZoneMembersOKCode int = 200

/*ZoneMembersOK 成功，返回成功信息

swagger:response zoneMembersOK
*/
type ZoneMembersOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2002 `json:"body,omitempty"`
}

// NewZoneMembersOK creates ZoneMembersOK with default headers values
func NewZoneMembersOK() *ZoneMembersOK {
	return &ZoneMembersOK{}
}

// WithPayload adds the payload to the zone members o k response
func (o *ZoneMembersOK) WithPayload(payload *models.InlineResponse2002) *ZoneMembersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone members o k response
func (o *ZoneMembersOK) SetPayload(payload *models.InlineResponse2002) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZoneMembersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrZoneMembersDefault 返回错误

swagger:response zoneMembersDefault
*/
type NrZoneMembersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrZoneMembersDefault creates NrZoneMembersDefault with default headers values
func NewNrZoneMembersDefault(code int) *NrZoneMembersDefault {
	if code <= 0 {
		code = 500
	}

	return &NrZoneMembersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the zone members default response
func (o *NrZoneMembersDefault) WithStatusCode(code int) *NrZoneMembersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the zone members default response
func (o *NrZoneMembersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the zone members default response
func (o *NrZoneMembersDefault) WithPayload(payload *models.Error) *NrZoneMembersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone members default response
func (o *NrZoneMembersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrZoneMembersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
