// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// ZoneApplyOKCode is the HTTP code returned for type ZoneApplyOK
const ZoneApplyOKCode int = 200

/*ZoneApplyOK 成功，返回成功信息

swagger:response zoneApplyOK
*/
type ZoneApplyOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewZoneApplyOK creates ZoneApplyOK with default headers values
func NewZoneApplyOK() *ZoneApplyOK {
	return &ZoneApplyOK{}
}

// WithPayload adds the payload to the zone apply o k response
func (o *ZoneApplyOK) WithPayload(payload *models.InlineResponse2004) *ZoneApplyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone apply o k response
func (o *ZoneApplyOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZoneApplyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrZoneApplyDefault 返回错误

swagger:response zoneApplyDefault
*/
type NrZoneApplyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrZoneApplyDefault creates NrZoneApplyDefault with default headers values
func NewNrZoneApplyDefault(code int) *NrZoneApplyDefault {
	if code <= 0 {
		code = 500
	}

	return &NrZoneApplyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the zone apply default response
func (o *NrZoneApplyDefault) WithStatusCode(code int) *NrZoneApplyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the zone apply default response
func (o *NrZoneApplyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the zone apply default response
func (o *NrZoneApplyDefault) WithPayload(payload *models.Error) *NrZoneApplyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone apply default response
func (o *NrZoneApplyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrZoneApplyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
