// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrZoneApplyHandlerFunc turns a function with the right signature into a zone apply handler
type NrZoneApplyHandlerFunc func(NrZoneApplyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrZoneApplyHandlerFunc) Handle(params NrZoneApplyParams) middleware.Responder {
	return fn(params)
}

// NrZoneApplyHandler interface for that can handle valid zone apply params
type NrZoneApplyHandler interface {
	Handle(NrZoneApplyParams) middleware.Responder
}

// NewNrZoneApply creates a new http.Handler for the zone apply operation
func NewNrZoneApply(ctx *middleware.Context, handler NrZoneApplyHandler) *NrZoneApply {
	return &NrZoneApply{Context: ctx, Handler: handler}
}

/*NrZoneApply swagger:route POST /zone/apply Zone zoneApply

申请加入圈子

申请加入圈子操作(非圈子成员)

*/
type NrZoneApply struct {
	Context *middleware.Context
	Handler NrZoneApplyHandler
}

func (o *NrZoneApply) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrZoneApplyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
