// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// ZoneUpdateOKCode is the HTTP code returned for type ZoneUpdateOK
const ZoneUpdateOKCode int = 200

/*ZoneUpdateOK 成功，返回成功信息

swagger:response zoneUpdateOK
*/
type ZoneUpdateOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewZoneUpdateOK creates ZoneUpdateOK with default headers values
func NewZoneUpdateOK() *ZoneUpdateOK {
	return &ZoneUpdateOK{}
}

// WithPayload adds the payload to the zone update o k response
func (o *ZoneUpdateOK) WithPayload(payload *models.InlineResponse2004) *ZoneUpdateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone update o k response
func (o *ZoneUpdateOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZoneUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrZoneUpdateDefault 返回错误

swagger:response zoneUpdateDefault
*/
type NrZoneUpdateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrZoneUpdateDefault creates NrZoneUpdateDefault with default headers values
func NewNrZoneUpdateDefault(code int) *NrZoneUpdateDefault {
	if code <= 0 {
		code = 500
	}

	return &NrZoneUpdateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the zone update default response
func (o *NrZoneUpdateDefault) WithStatusCode(code int) *NrZoneUpdateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the zone update default response
func (o *NrZoneUpdateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the zone update default response
func (o *NrZoneUpdateDefault) WithPayload(payload *models.Error) *NrZoneUpdateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone update default response
func (o *NrZoneUpdateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrZoneUpdateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
