// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// ZoneCreateOKCode is the HTTP code returned for type ZoneCreateOK
const ZoneCreateOKCode int = 200

/*ZoneCreateOK 成功，返回成功信息

swagger:response zoneCreateOK
*/
type ZoneCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewZoneCreateOK creates ZoneCreateOK with default headers values
func NewZoneCreateOK() *ZoneCreateOK {
	return &ZoneCreateOK{}
}

// WithPayload adds the payload to the zone create o k response
func (o *ZoneCreateOK) WithPayload(payload *models.InlineResponse2004) *ZoneCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone create o k response
func (o *ZoneCreateOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZoneCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrZoneCreateDefault 返回错误

swagger:response zoneCreateDefault
*/
type NrZoneCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrZoneCreateDefault creates NrZoneCreateDefault with default headers values
func NewNrZoneCreateDefault(code int) *NrZoneCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &NrZoneCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the zone create default response
func (o *NrZoneCreateDefault) WithStatusCode(code int) *NrZoneCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the zone create default response
func (o *NrZoneCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the zone create default response
func (o *NrZoneCreateDefault) WithPayload(payload *models.Error) *NrZoneCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the zone create default response
func (o *NrZoneCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrZoneCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
