// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrStatusLikeHandlerFunc turns a function with the right signature into a status like handler
type NrStatusLikeHandlerFunc func(NrStatusLikeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrStatusLikeHandlerFunc) Handle(params NrStatusLikeParams) middleware.Responder {
	return fn(params)
}

// NrStatusLikeHandler interface for that can handle valid status like params
type NrStatusLikeHandler interface {
	Handle(NrStatusLikeParams) middleware.Responder
}

// NewNrStatusLike creates a new http.Handler for the status like operation
func NewNrStatusLike(ctx *middleware.Context, handler NrStatusLikeHandler) *NrStatusLike {
	return &NrStatusLike{Context: ctx, Handler: handler}
}

/*NrStatusLike swagger:route POST /status/like Status statusLike

动态点赞

*/
type NrStatusLike struct {
	Context *middleware.Context
	Handler NrStatusLikeHandler
}

func (o *NrStatusLike) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrStatusLikeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
