// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// StatusLikeOKCode is the HTTP code returned for type StatusLikeOK
const StatusLikeOKCode int = 200

/*StatusLikeOK 成功，返回成功信息

swagger:response statusLikeOK
*/
type StatusLikeOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewStatusLikeOK creates StatusLikeOK with default headers values
func NewStatusLikeOK() *StatusLikeOK {
	return &StatusLikeOK{}
}

// WithPayload adds the payload to the status like o k response
func (o *StatusLikeOK) WithPayload(payload *models.InlineResponse2004) *StatusLikeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status like o k response
func (o *StatusLikeOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusLikeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrStatusLikeDefault 返回错误

swagger:response statusLikeDefault
*/
type NrStatusLikeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrStatusLikeDefault creates NrStatusLikeDefault with default headers values
func NewNrStatusLikeDefault(code int) *NrStatusLikeDefault {
	if code <= 0 {
		code = 500
	}

	return &NrStatusLikeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status like default response
func (o *NrStatusLikeDefault) WithStatusCode(code int) *NrStatusLikeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status like default response
func (o *NrStatusLikeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the status like default response
func (o *NrStatusLikeDefault) WithPayload(payload *models.Error) *NrStatusLikeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status like default response
func (o *NrStatusLikeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrStatusLikeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
