// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// StatusTagsOKCode is the HTTP code returned for type StatusTagsOK
const StatusTagsOKCode int = 200

/*StatusTagsOK 成功，返回成功信息

swagger:response statusTagsOK
*/
type StatusTagsOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2007 `json:"body,omitempty"`
}

// NewStatusTagsOK creates StatusTagsOK with default headers values
func NewStatusTagsOK() *StatusTagsOK {
	return &StatusTagsOK{}
}

// WithPayload adds the payload to the status tags o k response
func (o *StatusTagsOK) WithPayload(payload *models.InlineResponse2007) *StatusTagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status tags o k response
func (o *StatusTagsOK) SetPayload(payload *models.InlineResponse2007) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrStatusTagsDefault 返回错误

swagger:response statusTagsDefault
*/
type NrStatusTagsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrStatusTagsDefault creates NrStatusTagsDefault with default headers values
func NewNrStatusTagsDefault(code int) *NrStatusTagsDefault {
	if code <= 0 {
		code = 500
	}

	return &NrStatusTagsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status tags default response
func (o *NrStatusTagsDefault) WithStatusCode(code int) *NrStatusTagsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status tags default response
func (o *NrStatusTagsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the status tags default response
func (o *NrStatusTagsDefault) WithPayload(payload *models.Error) *NrStatusTagsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status tags default response
func (o *NrStatusTagsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrStatusTagsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
