// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrStatusRetweetHandlerFunc turns a function with the right signature into a status retweet handler
type NrStatusRetweetHandlerFunc func(NrStatusRetweetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrStatusRetweetHandlerFunc) Handle(params NrStatusRetweetParams) middleware.Responder {
	return fn(params)
}

// NrStatusRetweetHandler interface for that can handle valid status retweet params
type NrStatusRetweetHandler interface {
	Handle(NrStatusRetweetParams) middleware.Responder
}

// NewNrStatusRetweet creates a new http.Handler for the status retweet operation
func NewNrStatusRetweet(ctx *middleware.Context, handler NrStatusRetweetHandler) *NrStatusRetweet {
	return &NrStatusRetweet{Context: ctx, Handler: handler}
}

/*NrStatusRetweet swagger:route POST /status/retweet Status statusRetweet

转发动态

*/
type NrStatusRetweet struct {
	Context *middleware.Context
	Handler NrStatusRetweetHandler
}

func (o *NrStatusRetweet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrStatusRetweetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
