// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// StatusRetweetOKCode is the HTTP code returned for type StatusRetweetOK
const StatusRetweetOKCode int = 200

/*StatusRetweetOK 成功，返回成功信息

swagger:response statusRetweetOK
*/
type StatusRetweetOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewStatusRetweetOK creates StatusRetweetOK with default headers values
func NewStatusRetweetOK() *StatusRetweetOK {
	return &StatusRetweetOK{}
}

// WithPayload adds the payload to the status retweet o k response
func (o *StatusRetweetOK) WithPayload(payload *models.InlineResponse2004) *StatusRetweetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status retweet o k response
func (o *StatusRetweetOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusRetweetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrStatusRetweetDefault 返回错误

swagger:response statusRetweetDefault
*/
type NrStatusRetweetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrStatusRetweetDefault creates NrStatusRetweetDefault with default headers values
func NewNrStatusRetweetDefault(code int) *NrStatusRetweetDefault {
	if code <= 0 {
		code = 500
	}

	return &NrStatusRetweetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status retweet default response
func (o *NrStatusRetweetDefault) WithStatusCode(code int) *NrStatusRetweetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status retweet default response
func (o *NrStatusRetweetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the status retweet default response
func (o *NrStatusRetweetDefault) WithPayload(payload *models.Error) *NrStatusRetweetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status retweet default response
func (o *NrStatusRetweetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrStatusRetweetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
