// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// StatusTimelineOKCode is the HTTP code returned for type StatusTimelineOK
const StatusTimelineOKCode int = 200

/*StatusTimelineOK 成功，返回成功信息

swagger:response statusTimelineOK
*/
type StatusTimelineOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewStatusTimelineOK creates StatusTimelineOK with default headers values
func NewStatusTimelineOK() *StatusTimelineOK {
	return &StatusTimelineOK{}
}

// WithPayload adds the payload to the status timeline o k response
func (o *StatusTimelineOK) WithPayload(payload *models.InlineResponse2003) *StatusTimelineOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status timeline o k response
func (o *StatusTimelineOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusTimelineOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrStatusTimelineDefault 返回错误

swagger:response statusTimelineDefault
*/
type NrStatusTimelineDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrStatusTimelineDefault creates NrStatusTimelineDefault with default headers values
func NewNrStatusTimelineDefault(code int) *NrStatusTimelineDefault {
	if code <= 0 {
		code = 500
	}

	return &NrStatusTimelineDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status timeline default response
func (o *NrStatusTimelineDefault) WithStatusCode(code int) *NrStatusTimelineDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status timeline default response
func (o *NrStatusTimelineDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the status timeline default response
func (o *NrStatusTimelineDefault) WithPayload(payload *models.Error) *NrStatusTimelineDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status timeline default response
func (o *NrStatusTimelineDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrStatusTimelineDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
