// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	middleware "github.com/go-openapi/runtime/middleware"
	"injbackendapi/models"
	"fmt"
	"injbackendapi/var"
)

// NrStatusTimelineHandlerFunc turns a function with the right signature into a status timeline handler
type NrStatusTimelineHandlerFunc func(NrStatusTimelineParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrStatusTimelineHandlerFunc) Handle(params NrStatusTimelineParams) middleware.Responder {
	return fn(params)
}

// NrStatusTimelineHandler interface for that can handle valid status timeline params
type NrStatusTimelineHandler interface {
	Handle(NrStatusTimelineParams) middleware.Responder
}

// NewNrStatusTimeline creates a new http.Handler for the status timeline operation
func NewNrStatusTimeline(ctx *middleware.Context, handler NrStatusTimelineHandler) *NrStatusTimeline {
	return &NrStatusTimeline{Context: ctx, Handler: handler}
}

/*NrStatusTimeline swagger:route GET /status/timeline Status statusTimeline

获取动态列表

获取动态列表(0:热门  1:关注  2:好友  3:推荐  4:周边)

*/
type NrStatusTimeline struct {
	Context *middleware.Context
	Handler NrStatusTimelineHandler
}

func (o *NrStatusTimeline) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrStatusTimelineParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	var ok StatusTimelineOK
	var response models.InlineResponse2003
	var data models.InlineResponse2003Data
	var list models.InlineResponse2003DataPosts
	//var temp []*models.ZoneItem

	db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}
	defer db.Close()

	//var zoneList []models.ZoneItem
	db.Raw("select Content as text from btk_Posts").Find(&list)
	//fmt.Println("temp is",temp[0].Name)
	var count int64
	db.Raw("select PostID from btk_Posts").Count(&count)
	//status
	data.Posts = list
	data.TotalCount = count
	response.Data = &data
	var status models.Response
	status.UnmarshalBinary([]byte(_var.Response200(200,"ok")))
	response.Response = &status

	ok.SetPayload(&response)

	o.Context.Respond(rw, r, route.Produces, route, ok)

}
