// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// TopicShowOKCode is the HTTP code returned for type TopicShowOK
const TopicShowOKCode int = 200

/*TopicShowOK 成功，返回成功信息

swagger:response topicShowOK
*/
type TopicShowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2006 `json:"body,omitempty"`
}

// NewTopicShowOK creates TopicShowOK with default headers values
func NewTopicShowOK() *TopicShowOK {
	return &TopicShowOK{}
}

// WithPayload adds the payload to the topic show o k response
func (o *TopicShowOK) WithPayload(payload *models.InlineResponse2006) *TopicShowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic show o k response
func (o *TopicShowOK) SetPayload(payload *models.InlineResponse2006) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopicShowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrTopicShowDefault 返回错误

swagger:response topicShowDefault
*/
type NrTopicShowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrTopicShowDefault creates NrTopicShowDefault with default headers values
func NewNrTopicShowDefault(code int) *NrTopicShowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrTopicShowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the topic show default response
func (o *NrTopicShowDefault) WithStatusCode(code int) *NrTopicShowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the topic show default response
func (o *NrTopicShowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the topic show default response
func (o *NrTopicShowDefault) WithPayload(payload *models.Error) *NrTopicShowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic show default response
func (o *NrTopicShowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrTopicShowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
