// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// TopicFollowOKCode is the HTTP code returned for type TopicFollowOK
const TopicFollowOKCode int = 200

/*TopicFollowOK 成功，返回成功信息

swagger:response topicFollowOK
*/
type TopicFollowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewTopicFollowOK creates TopicFollowOK with default headers values
func NewTopicFollowOK() *TopicFollowOK {
	return &TopicFollowOK{}
}

// WithPayload adds the payload to the topic follow o k response
func (o *TopicFollowOK) WithPayload(payload *models.InlineResponse2004) *TopicFollowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic follow o k response
func (o *TopicFollowOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopicFollowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrTopicFollowDefault 返回错误

swagger:response topicFollowDefault
*/
type NrTopicFollowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrTopicFollowDefault creates NrTopicFollowDefault with default headers values
func NewNrTopicFollowDefault(code int) *NrTopicFollowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrTopicFollowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the topic follow default response
func (o *NrTopicFollowDefault) WithStatusCode(code int) *NrTopicFollowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the topic follow default response
func (o *NrTopicFollowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the topic follow default response
func (o *NrTopicFollowDefault) WithPayload(payload *models.Error) *NrTopicFollowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic follow default response
func (o *NrTopicFollowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrTopicFollowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
