// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// TopicSearchOKCode is the HTTP code returned for type TopicSearchOK
const TopicSearchOKCode int = 200

/*TopicSearchOK 成功，返回成功信息

swagger:response topicSearchOK
*/
type TopicSearchOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2005 `json:"body,omitempty"`
}

// NewTopicSearchOK creates TopicSearchOK with default headers values
func NewTopicSearchOK() *TopicSearchOK {
	return &TopicSearchOK{}
}

// WithPayload adds the payload to the topic search o k response
func (o *TopicSearchOK) WithPayload(payload *models.InlineResponse2005) *TopicSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic search o k response
func (o *TopicSearchOK) SetPayload(payload *models.InlineResponse2005) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopicSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrTopicSearchDefault 返回错误

swagger:response topicSearchDefault
*/
type NrTopicSearchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrTopicSearchDefault creates NrTopicSearchDefault with default headers values
func NewNrTopicSearchDefault(code int) *NrTopicSearchDefault {
	if code <= 0 {
		code = 500
	}

	return &NrTopicSearchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the topic search default response
func (o *NrTopicSearchDefault) WithStatusCode(code int) *NrTopicSearchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the topic search default response
func (o *NrTopicSearchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the topic search default response
func (o *NrTopicSearchDefault) WithPayload(payload *models.Error) *NrTopicSearchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic search default response
func (o *NrTopicSearchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrTopicSearchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
