// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// TopicListOKCode is the HTTP code returned for type TopicListOK
const TopicListOKCode int = 200

/*TopicListOK 成功，返回成功信息

swagger:response topicListOK
*/
type TopicListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2005 `json:"body,omitempty"`
}

// NewTopicListOK creates TopicListOK with default headers values
func NewTopicListOK() *TopicListOK {
	return &TopicListOK{}
}

// WithPayload adds the payload to the topic list o k response
func (o *TopicListOK) WithPayload(payload *models.InlineResponse2005) *TopicListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic list o k response
func (o *TopicListOK) SetPayload(payload *models.InlineResponse2005) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopicListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrTopicListDefault 返回错误

swagger:response topicListDefault
*/
type NrTopicListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrTopicListDefault creates NrTopicListDefault with default headers values
func NewNrTopicListDefault(code int) *NrTopicListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrTopicListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the topic list default response
func (o *NrTopicListDefault) WithStatusCode(code int) *NrTopicListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the topic list default response
func (o *NrTopicListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the topic list default response
func (o *NrTopicListDefault) WithPayload(payload *models.Error) *NrTopicListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic list default response
func (o *NrTopicListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrTopicListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
