// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrTopicFollowHandlerFunc turns a function with the right signature into a topic follow handler
type NrTopicFollowHandlerFunc func(NrTopicFollowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrTopicFollowHandlerFunc) Handle(params NrTopicFollowParams) middleware.Responder {
	return fn(params)
}

// NrTopicFollowHandler interface for that can handle valid topic follow params
type NrTopicFollowHandler interface {
	Handle(NrTopicFollowParams) middleware.Responder
}

// NewNrTopicFollow creates a new http.Handler for the topic follow operation
func NewNrTopicFollow(ctx *middleware.Context, handler NrTopicFollowHandler) *NrTopicFollow {
	return &NrTopicFollow{Context: ctx, Handler: handler}
}

/*NrTopicFollow swagger:route POST /topic/follow Topic topicFollow

关注话题

*/
type NrTopicFollow struct {
	Context *middleware.Context
	Handler NrTopicFollowHandler
}

func (o *NrTopicFollow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrTopicFollowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
