// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// TopicUnfollowOKCode is the HTTP code returned for type TopicUnfollowOK
const TopicUnfollowOKCode int = 200

/*TopicUnfollowOK 成功，返回成功信息

swagger:response topicUnfollowOK
*/
type TopicUnfollowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewTopicUnfollowOK creates TopicUnfollowOK with default headers values
func NewTopicUnfollowOK() *TopicUnfollowOK {
	return &TopicUnfollowOK{}
}

// WithPayload adds the payload to the topic unfollow o k response
func (o *TopicUnfollowOK) WithPayload(payload *models.InlineResponse2004) *TopicUnfollowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic unfollow o k response
func (o *TopicUnfollowOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopicUnfollowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrTopicUnfollowDefault 返回错误

swagger:response topicUnfollowDefault
*/
type NrTopicUnfollowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrTopicUnfollowDefault creates NrTopicUnfollowDefault with default headers values
func NewNrTopicUnfollowDefault(code int) *NrTopicUnfollowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrTopicUnfollowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the topic unfollow default response
func (o *NrTopicUnfollowDefault) WithStatusCode(code int) *NrTopicUnfollowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the topic unfollow default response
func (o *NrTopicUnfollowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the topic unfollow default response
func (o *NrTopicUnfollowDefault) WithPayload(payload *models.Error) *NrTopicUnfollowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the topic unfollow default response
func (o *NrTopicUnfollowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrTopicUnfollowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
