// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrTopicUnfollowHandlerFunc turns a function with the right signature into a topic unfollow handler
type NrTopicUnfollowHandlerFunc func(NrTopicUnfollowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrTopicUnfollowHandlerFunc) Handle(params NrTopicUnfollowParams) middleware.Responder {
	return fn(params)
}

// NrTopicUnfollowHandler interface for that can handle valid topic unfollow params
type NrTopicUnfollowHandler interface {
	Handle(NrTopicUnfollowParams) middleware.Responder
}

// NewNrTopicUnfollow creates a new http.Handler for the topic unfollow operation
func NewNrTopicUnfollow(ctx *middleware.Context, handler NrTopicUnfollowHandler) *NrTopicUnfollow {
	return &NrTopicUnfollow{Context: ctx, Handler: handler}
}

/*NrTopicUnfollow swagger:route POST /topic/unfollow Topic topicUnfollow

取消关注话题

*/
type NrTopicUnfollow struct {
	Context *middleware.Context
	Handler NrTopicUnfollowHandler
}

func (o *NrTopicUnfollow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrTopicUnfollowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
