// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrTopicSearchHandlerFunc turns a function with the right signature into a topic search handler
type NrTopicSearchHandlerFunc func(NrTopicSearchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrTopicSearchHandlerFunc) Handle(params NrTopicSearchParams) middleware.Responder {
	return fn(params)
}

// NrTopicSearchHandler interface for that can handle valid topic search params
type NrTopicSearchHandler interface {
	Handle(NrTopicSearchParams) middleware.Responder
}

// NewNrTopicSearch creates a new http.Handler for the topic search operation
func NewNrTopicSearch(ctx *middleware.Context, handler NrTopicSearchHandler) *NrTopicSearch {
	return &NrTopicSearch{Context: ctx, Handler: handler}
}

/*NrTopicSearch swagger:route GET /topic/search Topic topicSearch

搜索话题

搜索话题

*/
type NrTopicSearch struct {
	Context *middleware.Context
	Handler NrTopicSearchHandler
}

func (o *NrTopicSearch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrTopicSearchParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
