// Code generated by go-swagger; DO NOT EDIT.

package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrTopicListHandlerFunc turns a function with the right signature into a topic list handler
type NrTopicListHandlerFunc func(NrTopicListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrTopicListHandlerFunc) Handle(params NrTopicListParams) middleware.Responder {
	return fn(params)
}

// NrTopicListHandler interface for that can handle valid topic list params
type NrTopicListHandler interface {
	Handle(NrTopicListParams) middleware.Responder
}

// NewNrTopicList creates a new http.Handler for the topic list operation
func NewNrTopicList(ctx *middleware.Context, handler NrTopicListHandler) *NrTopicList {
	return &NrTopicList{Context: ctx, Handler: handler}
}

/*NrTopicList swagger:route GET /topic/list Topic topicList

获取话题列表(按最后一条动态的时间排序)

*/
type NrTopicList struct {
	Context *middleware.Context
	Handler NrTopicListHandler
}

func (o *NrTopicList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrTopicListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
