// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// CommentsListOKCode is the HTTP code returned for type CommentsListOK
const CommentsListOKCode int = 200

/*CommentsListOK 成功，返回成功信息

swagger:response commentsListOK
*/
type CommentsListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2009 `json:"body,omitempty"`
}

// NewCommentsListOK creates CommentsListOK with default headers values
func NewCommentsListOK() *CommentsListOK {
	return &CommentsListOK{}
}

// WithPayload adds the payload to the comments list o k response
func (o *CommentsListOK) WithPayload(payload *models.InlineResponse2009) *CommentsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the comments list o k response
func (o *CommentsListOK) SetPayload(payload *models.InlineResponse2009) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CommentsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrCommentsListDefault 返回错误

swagger:response commentsListDefault
*/
type NrCommentsListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrCommentsListDefault creates NrCommentsListDefault with default headers values
func NewNrCommentsListDefault(code int) *NrCommentsListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrCommentsListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the comments list default response
func (o *NrCommentsListDefault) WithStatusCode(code int) *NrCommentsListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the comments list default response
func (o *NrCommentsListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the comments list default response
func (o *NrCommentsListDefault) WithPayload(payload *models.Error) *NrCommentsListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the comments list default response
func (o *NrCommentsListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrCommentsListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
