// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	middleware "github.com/go-openapi/runtime/middleware"
	"injbackendapi/models"
	"fmt"
	"injbackendapi/var"
)

// NrCommentsListHandlerFunc turns a function with the right signature into a comments list handler
type NrCommentsListHandlerFunc func(NrCommentsListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrCommentsListHandlerFunc) Handle(params NrCommentsListParams) middleware.Responder {
	return fn(params)
}

// NrCommentsListHandler interface for that can handle valid comments list params
type NrCommentsListHandler interface {
	Handle(NrCommentsListParams) middleware.Responder
}

// NewNrCommentsList creates a new http.Handler for the comments list operation
func NewNrCommentsList(ctx *middleware.Context, handler NrCommentsListHandler) *NrCommentsList {
	return &NrCommentsList{Context: ctx, Handler: handler}
}

/*NrCommentsList swagger:route GET /comments/list Comment commentsList

获取评论列表

*/
type NrCommentsList struct {
	Context *middleware.Context
	Handler NrCommentsListHandler
}

func (o *NrCommentsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrCommentsListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	var ok CommentsListOK
	var response models.InlineResponse2009
	var data models.InlineResponse2009Data
	var list models.InlineResponse2009DataComments
	//var temp []*models.ZoneItem

	db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}
	defer db.Close()

	//var zoneList []models.ZoneItem
	db.Raw("select Content as content from btk_Comment").Find(&list)
	//fmt.Println("temp is",temp[0].Name)
	var count int64
	db.Raw("select CommentID from btk_Comment").Count(&count)
	//status
	data.Comments = list
	data.TotalCount = count
	response.Data = &data
	var status models.Response
	status.UnmarshalBinary([]byte(_var.Response200(200,"ok")))
	response.Response = &status

	ok.SetPayload(&response)

	o.Context.Respond(rw, r, route.Produces, route, ok)

}
