// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrCommentsDeleteHandlerFunc turns a function with the right signature into a comments delete handler
type NrCommentsDeleteHandlerFunc func(NrCommentsDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrCommentsDeleteHandlerFunc) Handle(params NrCommentsDeleteParams) middleware.Responder {
	return fn(params)
}

// NrCommentsDeleteHandler interface for that can handle valid comments delete params
type NrCommentsDeleteHandler interface {
	Handle(NrCommentsDeleteParams) middleware.Responder
}

// NewNrCommentsDelete creates a new http.Handler for the comments delete operation
func NewNrCommentsDelete(ctx *middleware.Context, handler NrCommentsDeleteHandler) *NrCommentsDelete {
	return &NrCommentsDelete{Context: ctx, Handler: handler}
}

/*NrCommentsDelete swagger:route POST /comments/delete Comment commentsDelete

删除评论

*/
type NrCommentsDelete struct {
	Context *middleware.Context
	Handler NrCommentsDeleteHandler
}

func (o *NrCommentsDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrCommentsDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
