// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrCommentsCreateHandlerFunc turns a function with the right signature into a comments create handler
type NrCommentsCreateHandlerFunc func(NrCommentsCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrCommentsCreateHandlerFunc) Handle(params NrCommentsCreateParams) middleware.Responder {
	return fn(params)
}

// NrCommentsCreateHandler interface for that can handle valid comments create params
type NrCommentsCreateHandler interface {
	Handle(NrCommentsCreateParams) middleware.Responder
}

// NewNrCommentsCreate creates a new http.Handler for the comments create operation
func NewNrCommentsCreate(ctx *middleware.Context, handler NrCommentsCreateHandler) *NrCommentsCreate {
	return &NrCommentsCreate{Context: ctx, Handler: handler}
}

/*NrCommentsCreate swagger:route POST /comments/create Comment commentsCreate

发起评论

*/
type NrCommentsCreate struct {
	Context *middleware.Context
	Handler NrCommentsCreateHandler
}

func (o *NrCommentsCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrCommentsCreateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
