// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrCommentsListHandlerFunc turns a function with the right signature into a comments list handler
type NrCommentsListHandlerFunc func(NrCommentsListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrCommentsListHandlerFunc) Handle(params NrCommentsListParams) middleware.Responder {
	return fn(params)
}

// NrCommentsListHandler interface for that can handle valid comments list params
type NrCommentsListHandler interface {
	Handle(NrCommentsListParams) middleware.Responder
}

// NewNrCommentsList creates a new http.Handler for the comments list operation
func NewNrCommentsList(ctx *middleware.Context, handler NrCommentsListHandler) *NrCommentsList {
	return &NrCommentsList{Context: ctx, Handler: handler}
}

/*NrCommentsList swagger:route GET /comments/list Comment commentsList

获取评论列表

*/
type NrCommentsList struct {
	Context *middleware.Context
	Handler NrCommentsListHandler
}

func (o *NrCommentsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrCommentsListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
