// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// CommentsDeleteOKCode is the HTTP code returned for type CommentsDeleteOK
const CommentsDeleteOKCode int = 200

/*CommentsDeleteOK 成功，返回成功信息

swagger:response commentsDeleteOK
*/
type CommentsDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewCommentsDeleteOK creates CommentsDeleteOK with default headers values
func NewCommentsDeleteOK() *CommentsDeleteOK {
	return &CommentsDeleteOK{}
}

// WithPayload adds the payload to the comments delete o k response
func (o *CommentsDeleteOK) WithPayload(payload *models.InlineResponse2004) *CommentsDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the comments delete o k response
func (o *CommentsDeleteOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CommentsDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrCommentsDeleteDefault 返回错误

swagger:response commentsDeleteDefault
*/
type NrCommentsDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrCommentsDeleteDefault creates NrCommentsDeleteDefault with default headers values
func NewNrCommentsDeleteDefault(code int) *NrCommentsDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &NrCommentsDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the comments delete default response
func (o *NrCommentsDeleteDefault) WithStatusCode(code int) *NrCommentsDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the comments delete default response
func (o *NrCommentsDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the comments delete default response
func (o *NrCommentsDeleteDefault) WithPayload(payload *models.Error) *NrCommentsDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the comments delete default response
func (o *NrCommentsDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrCommentsDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
