// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserUnfollowHandlerFunc turns a function with the right signature into a user unfollow handler
type NrUserUnfollowHandlerFunc func(NrUserUnfollowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserUnfollowHandlerFunc) Handle(params NrUserUnfollowParams) middleware.Responder {
	return fn(params)
}

// NrUserUnfollowHandler interface for that can handle valid user unfollow params
type NrUserUnfollowHandler interface {
	Handle(NrUserUnfollowParams) middleware.Responder
}

// NewNrUserUnfollow creates a new http.Handler for the user unfollow operation
func NewNrUserUnfollow(ctx *middleware.Context, handler NrUserUnfollowHandler) *NrUserUnfollow {
	return &NrUserUnfollow{Context: ctx, Handler: handler}
}

/*NrUserUnfollow swagger:route POST /user/unfollow User userUnfollow

取消关注

*/
type NrUserUnfollow struct {
	Context *middleware.Context
	Handler NrUserUnfollowHandler
}

func (o *NrUserUnfollow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserUnfollowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
