// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserShowOKCode is the HTTP code returned for type UserShowOK
const UserShowOKCode int = 200

/*UserShowOK 成功，返回成功信息

swagger:response userShowOK
*/
type UserShowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20012 `json:"body,omitempty"`
}

// NewUserShowOK creates UserShowOK with default headers values
func NewUserShowOK() *UserShowOK {
	return &UserShowOK{}
}

// WithPayload adds the payload to the user show o k response
func (o *UserShowOK) WithPayload(payload *models.InlineResponse20012) *UserShowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user show o k response
func (o *UserShowOK) SetPayload(payload *models.InlineResponse20012) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserShowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserShowDefault 返回错误

swagger:response userShowDefault
*/
type NrUserShowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserShowDefault creates NrUserShowDefault with default headers values
func NewNrUserShowDefault(code int) *NrUserShowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserShowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user show default response
func (o *NrUserShowDefault) WithStatusCode(code int) *NrUserShowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user show default response
func (o *NrUserShowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user show default response
func (o *NrUserShowDefault) WithPayload(payload *models.Error) *NrUserShowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user show default response
func (o *NrUserShowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserShowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
