// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserFriendsOKCode is the HTTP code returned for type UserFriendsOK
const UserFriendsOKCode int = 200

/*UserFriendsOK 成功，返回成功信息

swagger:response userFriendsOK
*/
type UserFriendsOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20013 `json:"body,omitempty"`
}

// NewUserFriendsOK creates UserFriendsOK with default headers values
func NewUserFriendsOK() *UserFriendsOK {
	return &UserFriendsOK{}
}

// WithPayload adds the payload to the user friends o k response
func (o *UserFriendsOK) WithPayload(payload *models.InlineResponse20013) *UserFriendsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user friends o k response
func (o *UserFriendsOK) SetPayload(payload *models.InlineResponse20013) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserFriendsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserFriendsDefault 返回错误

swagger:response userFriendsDefault
*/
type NrUserFriendsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserFriendsDefault creates NrUserFriendsDefault with default headers values
func NewNrUserFriendsDefault(code int) *NrUserFriendsDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserFriendsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user friends default response
func (o *NrUserFriendsDefault) WithStatusCode(code int) *NrUserFriendsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user friends default response
func (o *NrUserFriendsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user friends default response
func (o *NrUserFriendsDefault) WithPayload(payload *models.Error) *NrUserFriendsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user friends default response
func (o *NrUserFriendsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserFriendsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
