// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserFollowOKCode is the HTTP code returned for type UserFollowOK
const UserFollowOKCode int = 200

/*UserFollowOK 成功，返回成功信息

swagger:response userFollowOK
*/
type UserFollowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewUserFollowOK creates UserFollowOK with default headers values
func NewUserFollowOK() *UserFollowOK {
	return &UserFollowOK{}
}

// WithPayload adds the payload to the user follow o k response
func (o *UserFollowOK) WithPayload(payload *models.InlineResponse2004) *UserFollowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user follow o k response
func (o *UserFollowOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserFollowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserFollowDefault 返回错误

swagger:response userFollowDefault
*/
type NrUserFollowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserFollowDefault creates NrUserFollowDefault with default headers values
func NewNrUserFollowDefault(code int) *NrUserFollowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserFollowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user follow default response
func (o *NrUserFollowDefault) WithStatusCode(code int) *NrUserFollowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user follow default response
func (o *NrUserFollowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user follow default response
func (o *NrUserFollowDefault) WithPayload(payload *models.Error) *NrUserFollowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user follow default response
func (o *NrUserFollowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserFollowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
