// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserPhotosHandlerFunc turns a function with the right signature into a user photos handler
type NrUserPhotosHandlerFunc func(NrUserPhotosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserPhotosHandlerFunc) Handle(params NrUserPhotosParams) middleware.Responder {
	return fn(params)
}

// NrUserPhotosHandler interface for that can handle valid user photos params
type NrUserPhotosHandler interface {
	Handle(NrUserPhotosParams) middleware.Responder
}

// NewNrUserPhotos creates a new http.Handler for the user photos operation
func NewNrUserPhotos(ctx *middleware.Context, handler NrUserPhotosHandler) *NrUserPhotos {
	return &NrUserPhotos{Context: ctx, Handler: handler}
}

/*NrUserPhotos swagger:route GET /user/photos User userPhotos

获取用户的相册

*/
type NrUserPhotos struct {
	Context *middleware.Context
	Handler NrUserPhotosHandler
}

func (o *NrUserPhotos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserPhotosParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
