// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserShowHandlerFunc turns a function with the right signature into a user show handler
type NrUserShowHandlerFunc func(NrUserShowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserShowHandlerFunc) Handle(params NrUserShowParams) middleware.Responder {
	return fn(params)
}

// NrUserShowHandler interface for that can handle valid user show params
type NrUserShowHandler interface {
	Handle(NrUserShowParams) middleware.Responder
}

// NewNrUserShow creates a new http.Handler for the user show operation
func NewNrUserShow(ctx *middleware.Context, handler NrUserShowHandler) *NrUserShow {
	return &NrUserShow{Context: ctx, Handler: handler}
}

/*NrUserShow swagger:route GET /user/show User userShow

查看用户基本信息

*/
type NrUserShow struct {
	Context *middleware.Context
	Handler NrUserShowHandler
}

func (o *NrUserShow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserShowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
