// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserUnfollowOKCode is the HTTP code returned for type UserUnfollowOK
const UserUnfollowOKCode int = 200

/*UserUnfollowOK 成功，返回成功信息

swagger:response userUnfollowOK
*/
type UserUnfollowOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewUserUnfollowOK creates UserUnfollowOK with default headers values
func NewUserUnfollowOK() *UserUnfollowOK {
	return &UserUnfollowOK{}
}

// WithPayload adds the payload to the user unfollow o k response
func (o *UserUnfollowOK) WithPayload(payload *models.InlineResponse2004) *UserUnfollowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user unfollow o k response
func (o *UserUnfollowOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserUnfollowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserUnfollowDefault 返回错误

swagger:response userUnfollowDefault
*/
type NrUserUnfollowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserUnfollowDefault creates NrUserUnfollowDefault with default headers values
func NewNrUserUnfollowDefault(code int) *NrUserUnfollowDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserUnfollowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user unfollow default response
func (o *NrUserUnfollowDefault) WithStatusCode(code int) *NrUserUnfollowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user unfollow default response
func (o *NrUserUnfollowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user unfollow default response
func (o *NrUserUnfollowDefault) WithPayload(payload *models.Error) *NrUserUnfollowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user unfollow default response
func (o *NrUserUnfollowDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserUnfollowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
