// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserAggreeToFriendHandlerFunc turns a function with the right signature into a user aggree to friend handler
type NrUserAggreeToFriendHandlerFunc func(NrUserAggreeToFriendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserAggreeToFriendHandlerFunc) Handle(params NrUserAggreeToFriendParams) middleware.Responder {
	return fn(params)
}

// NrUserAggreeToFriendHandler interface for that can handle valid user aggree to friend params
type NrUserAggreeToFriendHandler interface {
	Handle(NrUserAggreeToFriendParams) middleware.Responder
}

// NewNrUserAggreeToFriend creates a new http.Handler for the user aggree to friend operation
func NewNrUserAggreeToFriend(ctx *middleware.Context, handler NrUserAggreeToFriendHandler) *NrUserAggreeToFriend {
	return &NrUserAggreeToFriend{Context: ctx, Handler: handler}
}

/*NrUserAggreeToFriend swagger:route POST /user/aggreeToFriend User userAggreeToFriend

同意好友申请

*/
type NrUserAggreeToFriend struct {
	Context *middleware.Context
	Handler NrUserAggreeToFriendHandler
}

func (o *NrUserAggreeToFriend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserAggreeToFriendParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
