// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserAggreeToFriendOKCode is the HTTP code returned for type UserAggreeToFriendOK
const UserAggreeToFriendOKCode int = 200

/*UserAggreeToFriendOK 成功，返回成功信息

swagger:response userAggreeToFriendOK
*/
type UserAggreeToFriendOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewUserAggreeToFriendOK creates UserAggreeToFriendOK with default headers values
func NewUserAggreeToFriendOK() *UserAggreeToFriendOK {
	return &UserAggreeToFriendOK{}
}

// WithPayload adds the payload to the user aggree to friend o k response
func (o *UserAggreeToFriendOK) WithPayload(payload *models.InlineResponse2004) *UserAggreeToFriendOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user aggree to friend o k response
func (o *UserAggreeToFriendOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserAggreeToFriendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserAggreeToFriendDefault 返回错误

swagger:response userAggreeToFriendDefault
*/
type NrUserAggreeToFriendDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserAggreeToFriendDefault creates NrUserAggreeToFriendDefault with default headers values
func NewNrUserAggreeToFriendDefault(code int) *NrUserAggreeToFriendDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserAggreeToFriendDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user aggree to friend default response
func (o *NrUserAggreeToFriendDefault) WithStatusCode(code int) *NrUserAggreeToFriendDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user aggree to friend default response
func (o *NrUserAggreeToFriendDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user aggree to friend default response
func (o *NrUserAggreeToFriendDefault) WithPayload(payload *models.Error) *NrUserAggreeToFriendDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user aggree to friend default response
func (o *NrUserAggreeToFriendDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserAggreeToFriendDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
