// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserRefuseToFriendHandlerFunc turns a function with the right signature into a user refuse to friend handler
type NrUserRefuseToFriendHandlerFunc func(NrUserRefuseToFriendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserRefuseToFriendHandlerFunc) Handle(params NrUserRefuseToFriendParams) middleware.Responder {
	return fn(params)
}

// NrUserRefuseToFriendHandler interface for that can handle valid user refuse to friend params
type NrUserRefuseToFriendHandler interface {
	Handle(NrUserRefuseToFriendParams) middleware.Responder
}

// NewNrUserRefuseToFriend creates a new http.Handler for the user refuse to friend operation
func NewNrUserRefuseToFriend(ctx *middleware.Context, handler NrUserRefuseToFriendHandler) *NrUserRefuseToFriend {
	return &NrUserRefuseToFriend{Context: ctx, Handler: handler}
}

/*NrUserRefuseToFriend swagger:route POST /user/refuseToFriend User userRefuseToFriend

拒绝好友申请

*/
type NrUserRefuseToFriend struct {
	Context *middleware.Context
	Handler NrUserRefuseToFriendHandler
}

func (o *NrUserRefuseToFriend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserRefuseToFriendParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
