// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserZonesOKCode is the HTTP code returned for type UserZonesOK
const UserZonesOKCode int = 200

/*UserZonesOK 成功，返回成功信息

swagger:response userZonesOK
*/
type UserZonesOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse200 `json:"body,omitempty"`
}

// NewUserZonesOK creates UserZonesOK with default headers values
func NewUserZonesOK() *UserZonesOK {
	return &UserZonesOK{}
}

// WithPayload adds the payload to the user zones o k response
func (o *UserZonesOK) WithPayload(payload *models.InlineResponse200) *UserZonesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user zones o k response
func (o *UserZonesOK) SetPayload(payload *models.InlineResponse200) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserZonesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserZonesDefault 返回错误

swagger:response userZonesDefault
*/
type NrUserZonesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserZonesDefault creates NrUserZonesDefault with default headers values
func NewNrUserZonesDefault(code int) *NrUserZonesDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserZonesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user zones default response
func (o *NrUserZonesDefault) WithStatusCode(code int) *NrUserZonesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user zones default response
func (o *NrUserZonesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user zones default response
func (o *NrUserZonesDefault) WithPayload(payload *models.Error) *NrUserZonesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user zones default response
func (o *NrUserZonesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserZonesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
