// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserDeleteFriendOKCode is the HTTP code returned for type UserDeleteFriendOK
const UserDeleteFriendOKCode int = 200

/*UserDeleteFriendOK 成功，返回成功信息

swagger:response userDeleteFriendOK
*/
type UserDeleteFriendOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewUserDeleteFriendOK creates UserDeleteFriendOK with default headers values
func NewUserDeleteFriendOK() *UserDeleteFriendOK {
	return &UserDeleteFriendOK{}
}

// WithPayload adds the payload to the user delete friend o k response
func (o *UserDeleteFriendOK) WithPayload(payload *models.InlineResponse2004) *UserDeleteFriendOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user delete friend o k response
func (o *UserDeleteFriendOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserDeleteFriendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserDeleteFriendDefault 返回错误

swagger:response userDeleteFriendDefault
*/
type NrUserDeleteFriendDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserDeleteFriendDefault creates NrUserDeleteFriendDefault with default headers values
func NewNrUserDeleteFriendDefault(code int) *NrUserDeleteFriendDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserDeleteFriendDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user delete friend default response
func (o *NrUserDeleteFriendDefault) WithStatusCode(code int) *NrUserDeleteFriendDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user delete friend default response
func (o *NrUserDeleteFriendDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user delete friend default response
func (o *NrUserDeleteFriendDefault) WithPayload(payload *models.Error) *NrUserDeleteFriendDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user delete friend default response
func (o *NrUserDeleteFriendDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserDeleteFriendDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
