// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injbackendapi/models"
)

// UserApplyFriendOKCode is the HTTP code returned for type UserApplyFriendOK
const UserApplyFriendOKCode int = 200

/*UserApplyFriendOK 成功，返回成功信息

swagger:response userApplyFriendOK
*/
type UserApplyFriendOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewUserApplyFriendOK creates UserApplyFriendOK with default headers values
func NewUserApplyFriendOK() *UserApplyFriendOK {
	return &UserApplyFriendOK{}
}

// WithPayload adds the payload to the user apply friend o k response
func (o *UserApplyFriendOK) WithPayload(payload *models.InlineResponse2004) *UserApplyFriendOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user apply friend o k response
func (o *UserApplyFriendOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserApplyFriendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrUserApplyFriendDefault 返回错误

swagger:response userApplyFriendDefault
*/
type NrUserApplyFriendDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrUserApplyFriendDefault creates NrUserApplyFriendDefault with default headers values
func NewNrUserApplyFriendDefault(code int) *NrUserApplyFriendDefault {
	if code <= 0 {
		code = 500
	}

	return &NrUserApplyFriendDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user apply friend default response
func (o *NrUserApplyFriendDefault) WithStatusCode(code int) *NrUserApplyFriendDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user apply friend default response
func (o *NrUserApplyFriendDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user apply friend default response
func (o *NrUserApplyFriendDefault) WithPayload(payload *models.Error) *NrUserApplyFriendDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user apply friend default response
func (o *NrUserApplyFriendDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrUserApplyFriendDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
