// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Body12 body 12
// swagger:model body_12
type Body12 struct {

	// 详细地址
	Address string `json:"address,omitempty"`

	// Ait的用户ID，可以为多个，中间以","分隔
	AitUsers string `json:"ait_users,omitempty"`

	// 动态内容
	Content string `json:"content,omitempty"`

	// 发帖人ID
	// Required: true
	Euid *string `json:"euid"`

	// 维度坐标
	Latitude float32 `json:"latitude,omitempty"`

	// 经度坐标
	Longitude float32 `json:"longitude,omitempty"`

	// oid
	Oid string `json:"oid,omitempty"`

	// 上传的图片(包含视频)ID数组
	PicIds []int64 `json:"pic_ids"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this body 12
func (m *Body12) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEuid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePicIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Body12) validateEuid(formats strfmt.Registry) error {

	if err := validate.Required("euid", "body", m.Euid); err != nil {
		return err
	}

	return nil
}

func (m *Body12) validatePicIds(formats strfmt.Registry) error {

	if swag.IsZero(m.PicIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Body12) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Body12) UnmarshalBinary(b []byte) error {
	var res Body12
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
