// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Body2 body 2
// swagger:model body_2
type Body2 struct {

	// 分类ID
	CategoryID int64 `json:"category_id,omitempty"`

	// 创建人ID
	// Required: true
	Euid *string `json:"euid"`

	// 上传的Logo图片ID
	// Required: true
	LogoID *int64 `json:"logo_id"`

	// 圈子名称
	// Required: true
	Name *string `json:"name"`

	// oid
	Oid string `json:"oid,omitempty"`

	// 上传的个性图片ID
	PicID int64 `json:"pic_id,omitempty"`

	// 圈子简介
	Remark string `json:"remark,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// 需要修改的圈子ID
	// Required: true
	ZoneID *int64 `json:"zone_id"`
}

// Validate validates this body 2
func (m *Body2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEuid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLogoID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateZoneID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Body2) validateEuid(formats strfmt.Registry) error {

	if err := validate.Required("euid", "body", m.Euid); err != nil {
		return err
	}

	return nil
}

func (m *Body2) validateLogoID(formats strfmt.Registry) error {

	if err := validate.Required("logo_id", "body", m.LogoID); err != nil {
		return err
	}

	return nil
}

func (m *Body2) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Body2) validateZoneID(formats strfmt.Registry) error {

	if err := validate.Required("zone_id", "body", m.ZoneID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Body2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Body2) UnmarshalBinary(b []byte) error {
	var res Body2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
