// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse2005Data inline response 200 5 data
// swagger:model inline_response_200_5_data
type InlineResponse2005Data struct {

	// topics
	Topics InlineResponse2005DataTopics `json:"topics"`

	// 返回总数量
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this inline response 200 5 data
func (m *InlineResponse2005Data) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse2005Data) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse2005Data) UnmarshalBinary(b []byte) error {
	var res InlineResponse2005Data
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
