// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Profile 用户个人资料
// swagger:model Profile
type Profile struct {

	// 用户头像
	// Required: true
	Avatar *string `json:"avatar"`

	// 出生日期(yyyy-MM-dd HH:mm:ss)
	Birthday string `json:"birthday,omitempty"`

	// 血型
	Blood string `json:"blood,omitempty"`

	// 公司名称
	CompanyName string `json:"companyName,omitempty"`

	// 最高学历
	Degree string `json:"degree,omitempty"`

	// 加密后的用户ID
	// Required: true
	Euid *string `json:"euid"`

	// 用户性别(0:保密 1:男 2:女)
	Gender int64 `json:"gender,omitempty"`

	// 家乡
	HomeArea string `json:"home_area,omitempty"`

	// 兴趣爱好
	Interest string `json:"interest,omitempty"`

	// 用户等级
	Level int64 `json:"level,omitempty"`

	// 婚姻状况
	Marriage string `json:"marriage,omitempty"`

	// 用户昵称
	// Required: true
	Nickname *string `json:"nickname"`

	// 现居城市
	NowArea string `json:"now_area,omitempty"`

	// 职业信息
	Profession string `json:"profession,omitempty"`

	// 个人说明
	Remark string `json:"remark,omitempty"`

	// 目前月薪
	Salary string `json:"salary,omitempty"`

	// 毕业学校
	School string `json:"school,omitempty"`

	// 体型
	Shape string `json:"shape,omitempty"`

	// 身高
	Stature int64 `json:"stature,omitempty"`

	// 体重
	Weight int64 `json:"weight,omitempty"`
}

// Validate validates this profile
func (m *Profile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvatar(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateEuid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateNickname(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Profile) validateAvatar(formats strfmt.Registry) error {

	if err := validate.Required("avatar", "body", m.Avatar); err != nil {
		return err
	}

	return nil
}

func (m *Profile) validateEuid(formats strfmt.Registry) error {

	if err := validate.Required("euid", "body", m.Euid); err != nil {
		return err
	}

	return nil
}

func (m *Profile) validateNickname(formats strfmt.Registry) error {

	if err := validate.Required("nickname", "body", m.Nickname); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Profile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Profile) UnmarshalBinary(b []byte) error {
	var res Profile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
