// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (

)

// AlbumItem album item
// swagger:model AlbumItem
type TimeLine struct {

	Who *string `json:"who"`

	When *string `json:"when"`

	What *string `json:"what"`

}
