// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TopicItem topic item
// swagger:model TopicItem
type TopicItem struct {

	// 话题简介
	Brief string `json:"brief,omitempty"`

	// 话题创建时间
	// Required: true
	CreatedAt *string `json:"created_at"`

	// 话题Logo路径
	Logo string `json:"logo,omitempty"`

	// 话题标题
	// Required: true
	Name *string `json:"name"`

	// 话题个性图片路径
	Photo string `json:"photo,omitempty"`

	// 话题ID
	// Required: true
	Tid *int64 `json:"tid"`
}

// Validate validates this topic item
func (m *TopicItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TopicItem) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	return nil
}

func (m *TopicItem) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *TopicItem) validateTid(formats strfmt.Registry) error {

	if err := validate.Required("tid", "body", m.Tid); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TopicItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TopicItem) UnmarshalBinary(b []byte) error {
	var res TopicItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
